# Generated by Django 4.1 on 2024-02-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoira'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='categoira',
            new_name='categoria',
        ),
    ]
